formatter: "markdown"

recursive:
  enabled: true
  path: "./"

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

output:
  file: "README.md"
  mode: append

sort:
  enabled: true
  by: required

settings:
  color: true
  hide-empty: true
