name: Generate terraform docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.0"
      - run: go install github.com/terraform-docs/terraform-docs@v0.17.0
      - run: $(go env GOPATH)/bin/terraform-docs markdown -c .terraform-docs.yml .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "👻 (Module READMEs): Automated Terraform Documentation"

  create-semantic-tag:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "New tag ${{ steps.tag_version.outputs.new_tag }}"
